server:
  port: 9093

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: commerce-service
          uri: http://localhost:8081/
          predicates:
            - Path=/start

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
