global:
  scrape_interval: 5s
  evaluation_interval: 5s
  #scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'Commerce service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8081' ]