spring:
  application:
    name: commerce-service
  config:
    import: "optional:configserver:http://localhost:9092/"
#actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
